# Vanguard A/B Testing

# Load Query Results

In [25]:
import pandas as pd

In [26]:
df=pd.read_csv("Raw_data/df_final_demo.csv")

# Explore Data

In [27]:
df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  object
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ MB

In [29]:
df.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,7.060900e+04,70595.000000,70595.000000,70594.000000,70595.000000,7.059500e+04,70595.000000,70595.000000
mean,5.004992e+06,12.052950,150.659367,46.442240,2.255528,1.474452e+05,3.382478,5.566740
std,2.877278e+06,6.871819,82.089854,15.591273,0.534997,3.015087e+05,2.236580,2.353286
min,1.690000e+02,2.000000,33.000000,13.500000,1.000000,1.378942e+04,0.000000,1.000000
25%,2.519329e+06,6.000000,82.000000,32.500000,2.000000,3.734683e+04,1.000000,4.000000
50%,5.016978e+06,11.000000,136.000000,47.000000,2.000000,6.333290e+04,3.000000,5.000000
75%,7.483085e+06,16.000000,192.000000,59.000000,2.000000,1.375449e+05,6.000000,7.000000
max,9.999839e+06,62.000000,749.000000,96.000000,8.000000,1.632004e+07,7.000000,9.000000

In [30]:
df.dtypes

client_id             int64
clnt_tenure_yr      float64
clnt_tenure_mnth    float64
clnt_age            float64
gendr                object
num_accts           float64
bal                 float64
calls_6_mnth        float64
logons_6_mnth       float64
dtype: object

# Clean Data

In [31]:
df = df.rename(columns={
    'gendr': 'gender',
    'clnt_age':'client_age',
    'clnt_tenure_yr': 'client_tenure_yr',
    'clnt_tenure_mnth': 'client_tenure_month',
    'bal':'balance'
})

In [32]:
print(df.columns.tolist())

['client_id', 'client_tenure_yr', 'client_tenure_month', 'client_age', 'gender', 'num_accts', 'balance', 'calls_6_mnth', 'logons_6_mnth']

In [33]:
df.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [34]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
70604    False
70605    False
70606    False
70607    False
70608    False
Length: 70609, dtype: bool

In [35]:
df.isnull().sum()

client_id               0
client_tenure_yr       14
client_tenure_month    14
client_age             15
gender                 14
num_accts              14
balance                14
calls_6_mnth           14
logons_6_mnth          14
dtype: int64

In [36]:
df.dropna(subset=['client_tenure_yr','client_tenure_month','client_age','gender','num_accts','balance','calls_6_mnth','logons_6_mnth'] ,inplace=True)

In [37]:
df.isnull().sum()

client_id              0
client_tenure_yr       0
client_tenure_month    0
client_age             0
gender                 0
num_accts              0
balance                0
calls_6_mnth           0
logons_6_mnth          0
dtype: int64

In [38]:
df['client_age'] = df['client_age'].round().astype(int)

In [39]:
df['num_accts'] = df['num_accts'].astype(int)

In [40]:
df['calls_6_mnth'] = df['calls_6_mnth'].astype(int)
df['logons_6_mnth'] = df['logons_6_mnth'].astype(int)

In [41]:
df.dtypes

client_id                int64
client_tenure_yr       float64
client_tenure_month    float64
client_age               int64
gender                  object
num_accts                int64
balance                float64
calls_6_mnth             int64
logons_6_mnth            int64
dtype: object

In [42]:
df['gender'] = df['gender'].replace({
    'U': 'Unknown',
    'M': 'Male',
    'F': 'Female'
})

In [43]:
df.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3

In [44]:
df.to_csv("cleaned_demo.csv",index=False)

# Load Experiment_client Data

In [45]:
df1=pd.read_csv("Raw_data/df_final_experiment_clients (1).csv")

# Explore Data

In [46]:
df1.shape

(70609, 2)

In [47]:
df1.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [48]:
df1.dtypes

client_id     int64
Variation    object
dtype: object

# Clean Data

In [49]:
df1.isnull().sum()

client_id        0
Variation    20109
dtype: int64

In [50]:
df1.dropna(subset=['Variation'],inplace=True)

In [51]:
df1.isnull().sum()

client_id    0
Variation    0
dtype: int64

In [52]:
df1.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
50495    False
50496    False
50497    False
50498    False
50499    False
Length: 50500, dtype: bool

In [53]:
df1.to_csv("cleaned_experiment.csv",index=False)

# Merge Data Demo and Experiment_client

In [54]:
Merged=pd.merge(df,df1,on='client_id',how='inner')

In [55]:
Merged.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control

In [56]:
Merged.shape

(50487, 10)

In [57]:
Merged['Variation'].value_counts()

Variation
Test       26961
Control    23526
Name: count, dtype: int64

In [58]:
Merged['gender'].value_counts()

gender
Unknown    17280
Male       16947
Female     16258
X              2
Name: count, dtype: int64

In [59]:
Merged = Merged[Merged['gender'] != 'X']

In [60]:
Merged['gender'].value_counts()

gender
Unknown    17280
Male       16947
Female     16258
Name: count, dtype: int64

In [61]:
Merged.groupby('Variation')[['gender']].count()

           gender
Variation
Control     23526
Test        26959

In [62]:
Merged.groupby(['Variation', 'gender']).size().reset_index(name='count')

  Variation   gender  count
0   Control   Female   7542
1   Control     Male   7970
2   Control  Unknown   8014
3      Test   Female   8716
4      Test     Male   8977
5      Test  Unknown   9266

In [63]:
Merged.groupby(['Variation', 'gender']).size().groupby(level=0).apply(lambda x: (x / x.sum() * 100).round(1))

Variation  Variation  gender
Control    Control    Female     32.1
                      Male       33.9
                      Unknown    34.1
Test       Test       Female     32.3
                      Male       33.3
                      Unknown    34.4
dtype: float64

In [64]:
Merged.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control

In [65]:
Merged.shape

(50485, 10)

In [67]:
Merged.to_csv("Merged.csv",index=False)