In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("df_final_demo.csv")

In [15]:
df.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [21]:
df = df.rename(columns={
    'gendr': 'gender',
    'clnt_age':'client_age',
    'clnt_tenure_yr': 'client_tenure_yr',
    'clnt_tenure_mnth': 'client_tenure_month'
})

In [22]:
print(df.columns.tolist())

['client_id', 'client_tenure_yr', 'client_tenure_month', 'client_age', 'gender', 'num_accts', 'bal', 'calls_6_mnth', 'logons_6_mnth']

In [23]:
df.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [27]:
df.info

<bound method DataFrame.info of        client_id  clnt_tenure_yr  clnt_tenure_mnth  clnt_age gender  \
0         836976             6.0              73.0        60      U
1        2304905             7.0              94.0        58      U
2        1439522             5.0              64.0        32      U
3        1562045            16.0             198.0        49      M
4        5126305            12.0             145.0        33      F
...          ...             ...               ...       ...    ...
70604    7993686             4.0              56.0        38      U
70605    8981690            12.0             148.0        31      M
70606     333913            16.0             198.0        62      F
70607    1573142            21.0             255.0        68      M
70608    5602139            21.0             254.0        60      F

       num_accts         bal  calls_6_mnth  logons_6_mnth
0              2    45105.30             6              9
1              2   110860.30             6              9
2              2    52467.79             6              9
3              2    67454.65             3              6
4              2   103671.75             0              3
...          ...         ...           ...            ...
70604          3  1411062.68             5              5
70605          2   101867.07             6              6
70606          2    40745.00             3              3
70607          3   475114.69             4              4
70608          3   157498.73             7              7

[70594 rows x 9 columns]>

In [24]:
df.describe()

,client_id,client_tenure_yr,client_tenure_month,client_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,7.060900e+04,70595.000000,70595.000000,70594.000000,70595.000000,7.059500e+04,70595.000000,70595.000000
mean,5.004992e+06,12.052950,150.659367,46.442240,2.255528,1.474452e+05,3.382478,5.566740
std,2.877278e+06,6.871819,82.089854,15.591273,0.534997,3.015087e+05,2.236580,2.353286
min,1.690000e+02,2.000000,33.000000,13.500000,1.000000,1.378942e+04,0.000000,1.000000
25%,2.519329e+06,6.000000,82.000000,32.500000,2.000000,3.734683e+04,1.000000,4.000000
50%,5.016978e+06,11.000000,136.000000,47.000000,2.000000,6.333290e+04,3.000000,5.000000
75%,7.483085e+06,16.000000,192.000000,59.000000,2.000000,1.375449e+05,6.000000,7.000000
max,9.999839e+06,62.000000,749.000000,96.000000,8.000000,1.632004e+07,7.000000,9.000000

In [25]:
df.dtypes

client_id                int64
client_tenure_yr       float64
client_tenure_month    float64
client_age             float64
gender                  object
num_accts              float64
bal                    float64
calls_6_mnth           float64
logons_6_mnth          float64
dtype: object

In [26]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
70604    False
70605    False
70606    False
70607    False
70608    False
Length: 70609, dtype: bool

In [27]:
df.isnull().sum()

client_id               0
client_tenure_yr       14
client_tenure_month    14
client_age             15
gender                 14
num_accts              14
bal                    14
calls_6_mnth           14
logons_6_mnth          14
dtype: int64

In [29]:
df.dropna(subset=['client_tenure_yr','client_tenure_month','client_age','gender','num_accts','bal','calls_6_mnth','logons_6_mnth'] ,inplace=True)

In [30]:
df.isnull().sum()

client_id              0
client_tenure_yr       0
client_tenure_month    0
client_age             0
gender                 0
num_accts              0
bal                    0
calls_6_mnth           0
logons_6_mnth          0
dtype: int64

In [31]:
df['client_age'] = df['client_age'].round().astype(int)

In [32]:
df['num_accts'] = df['num_accts'].astype(int)

In [33]:
df['calls_6_mnth'] = df['calls_6_mnth'].astype(int)
df['logons_6_mnth'] = df['logons_6_mnth'].astype(int)

In [34]:
df.dtypes

client_id                int64
client_tenure_yr       float64
client_tenure_month    float64
client_age               int64
gender                  object
num_accts                int64
bal                    float64
calls_6_mnth             int64
logons_6_mnth            int64
dtype: object

In [35]:
df1=pd.read_csv("df_final_experiment_clients (1).csv")

In [36]:
df1.shape

(70609, 2)

In [37]:
df1.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [38]:
df1.isnull().sum()

client_id        0
Variation    20109
dtype: int64

In [39]:
df1.dropna(subset=['Variation'],inplace=True)

In [40]:
df1.dtypes

client_id     int64
Variation    object
dtype: object

In [41]:
df1.isnull().sum()

client_id    0
Variation    0
dtype: int64

In [42]:
df1.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
50495    False
50496    False
50497    False
50498    False
50499    False
Length: 50500, dtype: bool

In [43]:
Merged=pd.merge(df,df1,on='client_id',how='inner')

In [44]:
Merged.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,U,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,U,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,U,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,M,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,F,2,103671.75,0,3,Control

In [45]:
Merged.shape

(50487, 10)

In [46]:
Merged['Variation'].value_counts()

Variation
Test       26961
Control    23526
Name: count, dtype: int64

In [47]:
Merged['gender'].value_counts()

gender
U    17280
M    16947
F    16258
X        2
Name: count, dtype: int64

In [48]:
Merged.groupby('Variation')[['gender']].count()

           gender
Variation
Control     23526
Test        26961

In [49]:
Merged.groupby(['Variation', 'gender']).size().reset_index(name='count')

  Variation gender  count
0   Control      F   7542
1   Control      M   7970
2   Control      U   8014
3      Test      F   8716
4      Test      M   8977
5      Test      U   9266
6      Test      X      2

In [50]:
Merged.groupby(['Variation', 'gender']).size().groupby(level=0).apply(lambda x: (x / x.sum() * 100).round(1))

Variation  Variation  gender
Control    Control    F         32.1
                      M         33.9
                      U         34.1
Test       Test       F         32.3
                      M         33.3
                      U         34.4
                      X          0.0
dtype: float64

In [74]:
Merged['gender'] = Merged['gender'].replace('U', 'Unknown')

In [75]:
Merged.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,UNKNOWN,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,UNKNOWN,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,UNKNOWN,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,M,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,F,2,103671.75,0,3,Control

In [76]:
Merged['gender'] = Merged['gender'].str.strip().str.upper()
Merged = Merged[Merged['gender'] != 'X']

In [77]:
Merged.groupby(['Variation', 'gender']).size().reset_index(name='count')

  Variation   gender  count
0   Control        F   7542
1   Control        M   7970
2   Control  UNKNOWN   8014
3      Test        F   8716
4      Test        M   8977
5      Test  UNKNOWN   9266

In [78]:
Merged.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,UNKNOWN,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,UNKNOWN,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,UNKNOWN,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,M,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,F,2,103671.75,0,3,Control

In [79]:
Merged.shape

(50485, 10)

In [80]:
Merged.to_csv(r"C:\Users\HP\OneDrive\Desktop\git-practice\Vanguard self version\Merged.csv",index=False, encoding="utf-8")