# Cleaning the Data
-  data cleaning of demo + experiment files

In [464]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import os

In [465]:
os.getcwd()  # this prints your current working directory

'/Users/hanane/Ironhack/vanguard_abtest_project'

In [466]:
os.listdir('raw_data')

['df_final_experiment_clients.csv',
 'df_final_demo.csv',
 'df_final_web_data_pt_1.csv',
 'df_final_web_data_pt_2.csv']

In [467]:
df_demo = pd.read_csv('clean_data/demo_exp_merged.csv')
df_exp = pd.read_csv('raw_data/df_final_experiment_clients.csv')
df_web1 = pd.read_csv('raw_data/df_final_web_data_pt_1.csv')
df_web2 = pd.read_csv('raw_data/df_final_web_data_pt_2.csv')

In [468]:
df_demo.head(5)

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control

## df_exp cleaning

In [469]:
df_exp.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [470]:
df_exp.columns = df_exp.columns.str.lower().str.strip()

In [471]:
df_exp['variation'].value_counts(dropna=False)

variation
Test       26968
Control    23532
NaN        20109
Name: count, dtype: int64

In [472]:
df_exp.isnull().sum()

client_id        0
variation    20109
dtype: int64

In [473]:
df_exp = df_exp.dropna(subset=['variation'])
df_exp.isnull().sum()

client_id    0
variation    0
dtype: int64

In [474]:
df_exp.variation.value_counts()

variation
Test       26968
Control    23532
Name: count, dtype: int64

In [475]:
df_exp.duplicated().sum()

np.int64(0)

In [476]:
df_exp.to_csv("clean_data/cleaned_experiment.csv",index=False)

In [477]:
df_exp.shape

(50500, 2)

## df_web cleaning

In [478]:
df_web1.head(3)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22

In [479]:
df_web2.head(3)

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48

In [480]:
#merging the two web datasets
df_web = pd.concat([df_web1, df_web2], axis=0 )

In [481]:
df_web.shape

(755405, 5)

In [482]:
df_web.duplicated().sum()

np.int64(10764)

In [483]:
df_web = df_web.drop_duplicates()
df_web.duplicated().sum()

np.int64(0)

In [484]:
df_web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [485]:
df_web.dtypes

client_id        int64
visitor_id      object
visit_id        object
process_step    object
date_time       object
dtype: object

In [486]:
df_web['date_time'] =pd.to_datetime(df_web['date_time'])
print(df_web.date_time.dtype)

datetime64[ns]

In [487]:
df_web['process_step'].value_counts()

process_step
start      234999
step_1     162797
step_2     132750
step_3     111589
confirm    102506
Name: count, dtype: int64

In [488]:
df_web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [489]:
df_web.head(10)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05
9,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43

In [490]:
df_web.to_csv("clean_data/cleaned_web.csv",index=False)

In [491]:
df_web.shape

(744641, 5)

In [492]:
df_exp.shape

(50500, 2)

## Merging df_web and df_exp

In [493]:
df= df_exp.merge(df_web, on='client_id', how='inner')
print(df.shape)

(317235, 6)

In [494]:
df.variation.value_counts()

variation
Test       176699
Control    140536
Name: count, dtype: int64

In [495]:
df.head(10)

,client_id,variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,Test,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,9988021,Test,580560515_7732621733,219729223_42518459208_211914,start,2017-04-12 18:54:43
9,9988021,Test,580560515_7732621733,219729223_42518459208_211914,start,2017-04-12 18:38:42

In [496]:
df.to_csv("clean_data/exp_web_merged.csv",index=False)

# Completion rate
reached "confirm" 
gone through all the step in the right order
loops are accepted

In [497]:
df.head(3)

,client_id,variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22

In [498]:
df_sorted = df.sort_values(['visit_id', 'date_time'])

In [499]:
ordered_steps = df_sorted.groupby('visit_id')['process_step'].apply(list)

In [500]:
required_order = ['start', 'step_1', 'step_2', 'step_3', 'confirm']

def is_complete_in_order(steps_sequence, required=required_order):
    """
    Returns True if the required steps appear in the correct order
    within the user's sequence. Repeats and loops are allowed between steps.
    """
    required_index = 0
    
    for step in steps_sequence:
        if step == required[required_index]:
            required_index += 1
            if required_index == len(required):
                return True
    
    return False

In [501]:
completed = ordered_steps.apply(is_complete_in_order)
completed.head()

visit_id
100012776_37918976071_457913    False
100019538_17884295066_43909      True
100022086_87870757897_149620     True
100030127_47967100085_936361    False
100037962_47432393712_705583    False
Name: process_step, dtype: bool

In [502]:
completion_rate = completed.mean()
completion_rate

np.float64(0.4700816414998916)

In [503]:
completion_rate_by_variation = completed.groupby(df_sorted.groupby('visit_id')['variation'].first()).mean()
completion_rate_by_variation

variation
Control    0.458562
Test       0.480059
Name: process_step, dtype: float64

In [504]:
completion_rate_v2 = (completion_rate_by_variation * 100).round(2)
completion_rate_v2

variation
Control    45.86
Test       48.01
Name: process_step, dtype: float64

In [505]:
df.head()

,client_id,variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

# Time spent per step

In [506]:
df_web.shape

(744641, 5)

In [507]:
# Sort chronologically
df = df.sort_values(['visit_id', 'date_time'])
df.head(5)

,client_id,variation,visitor_id,visit_id,process_step,date_time
140614,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17
140613,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:23:09
311202,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56
311201,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12
311200,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21

In [508]:
df['next_time'] = df.groupby('visit_id')['date_time'].shift(-1)

In [509]:
df['time_spent_clean'] = (df['next_time'] - df['date_time']).dt.total_seconds()

In [510]:
df.head(5)

,client_id,variation,visitor_id,visit_id,process_step,date_time,next_time,time_spent_clean
140614,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,2017-04-26 13:23:09,52.0
140613,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:23:09,NaT,NaN
311202,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0
311201,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0
311200,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0

In [511]:
# handeling last step ( confirm) 
df = df[df['time_spent_clean'].notna()]

In [512]:
# fixing repeated steps
step_time_per_visit = (
    df.groupby(['visit_id', 'process_step'])['time_spent_clean']
    .sum()
    .reset_index())

In [513]:
df.head(5)

,client_id,variation,visitor_id,visit_id,process_step,date_time,next_time,time_spent_clean
140614,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,2017-04-26 13:23:09,52.0
311202,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0
311201,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0
311200,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0
311199,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:35,2017-04-09 16:21:41,6.0

In [514]:
# final aggregation
final_step_time = (step_time_per_visit.groupby('process_step')['time_spent_clean']
                   .mean()
                   .reset_index())
final_step_time

  process_step  time_spent_clean
0      confirm        305.410080
1        start         93.875809
2       step_1         73.916580
3       step_2        114.930287
4       step_3        157.701116

In [515]:
#handeling the loop ( step1-step2-step1) 
#df_first = df.drop_duplicates(subset=['visit_id', 'process_step'], keep='first')

# Error rate

In [516]:
df.head()

,client_id,variation,visitor_id,visit_id,process_step,date_time,next_time,time_spent_clean
140614,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,2017-04-26 13:23:09,52.0
311202,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0
311201,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0
311200,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0
311199,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:35,2017-04-09 16:21:41,6.0

In [517]:
df_sorted = df.sort_values(['visit_id', 'date_time']).reset_index(drop=True)

In [518]:
# 2. Map each step to a numeric rank
step_rank = {'start': 0, 'step_1': 1, 'step_2': 2, 'step_3': 3, 'confirm': 4}
df_sorted['step_rank'] = df_sorted['process_step'].map(step_rank)

In [519]:
# 3. Get the previous step and its rank within each visit
df_sorted['prev_step'] = df_sorted.groupby('visit_id')['process_step'].shift(1)
df_sorted['prev_rank'] = df_sorted.groupby('visit_id')['step_rank'].shift(1)

In [520]:
df_sorted.head(5)

,client_id,variation,visitor_id,visit_id,process_step,date_time,next_time,time_spent_clean,step_rank,prev_step,prev_rank
0,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,2017-04-26 13:23:09,52.0,4,NaN,NaN
1,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0,0,NaN,NaN
2,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0,1,start,0.0
3,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0,2,step_1,1.0
4,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:35,2017-04-09 16:21:41,6.0,1,step_2,2.0

In [521]:
# 4. Compute backward distance (weighted: step_3 -> step_1 = 2 errors)
df_sorted['backward_distance'] = df_sorted['prev_rank'] - df_sorted['step_rank']
df_sorted.loc[df_sorted['backward_distance'] < 0, 'backward_distance'] = 0
df_sorted['backward_distance'] = df_sorted['backward_distance'].fillna(0)

In [522]:
df_sorted.head(5)

,client_id,variation,visitor_id,visit_id,process_step,date_time,next_time,time_spent_clean,step_rank,prev_step,prev_rank,backward_distance
0,3561384,Test,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,2017-04-26 13:23:09,52.0,4,NaN,NaN,0.0
1,7338123,Test,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0,0,NaN,NaN,0.0
2,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0,1,start,0.0,0.0
3,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0,2,step_1,1.0,0.0
4,7338123,Test,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:35,2017-04-09 16:21:41,6.0,1,step_2,2.0,1.0

In [523]:
len(df_sorted)

248030

In [524]:
df_sorted['backward_distance'].sum()

np.float64(28681.0)

In [525]:
# A.Overall weighted error rate
overall_error_rate = df_sorted['backward_distance'].sum()*100 / len(df_sorted)
overall_error_rate

np.float64(11.563520541869934)

In [526]:
# B. Overall error rate per variation
error_by_variation = df_sorted.groupby('variation')['backward_distance'].mean()
error_by_variation

variation
Control    0.111345
Test       0.118966
Name: backward_distance, dtype: float64

In [527]:
error_by_step = (
    df_sorted.groupby('prev_step')['backward_distance']
    .agg(total_errors='sum', transitions='count', error_rate='mean')
    .reindex(['start', 'step_1', 'step_2', 'step_3', 'confirm'])
)
error_by_step

           total_errors  transitions  error_rate
prev_step
start               0.0        70300    0.000000
step_1           6378.0        56251    0.113385
step_2           6942.0        48890    0.141992
step_3          12394.0        12447    0.995742
confirm          2967.0         2322    1.277778

- prev_step = step_3 → the step they left
- process_step = start → the step they landed on
- backward_distance = 3 → the size of the jump

In [528]:
error_by_step_and_variation = (
    df_sorted.groupby(['variation', 'prev_step'])['backward_distance']
    .mean()
    .unstack('variation')
    .reindex(['start', 'step_1', 'step_2', 'step_3', 'confirm'])
)
error_by_step_and_variation

variation   Control      Test
prev_step
start      0.000000  0.000000
step_1     0.071579  0.143903
step_2     0.106566  0.170809
step_3     1.059394  0.940647
confirm    1.935354  0.789039