# Cleaning the Data
-  data cleaning of demo + experiment files

In [82]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import os

In [83]:
os.getcwd()  # this prints your current working directory

'/Users/hanane/Ironhack/vanguard_abtest_project'

In [84]:
os.listdir('raw_data')

['df_final_experiment_clients.csv',
 'df_final_demo.csv',
 'df_final_web_data_pt_1.csv',
 'df_final_web_data_pt_2.csv']

In [85]:
df_demo = pd.read_csv('clean_data/demo_exp_merged.csv')
df_exp = pd.read_csv('raw_data/df_final_experiment_clients.csv')
df_web1 = pd.read_csv('raw_data/df_final_web_data_pt_1.csv')
df_web2 = pd.read_csv('raw_data/df_final_web_data_pt_2.csv')

In [86]:
df_demo.head(5)

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9,Test
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9,Control
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9,Test
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6,Test
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3,Control

## df_exp cleaning

In [87]:
df_exp.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [88]:
df_exp.columns = df_exp.columns.str.lower().str.strip()

In [89]:
df_exp['variation'].value_counts(dropna=False)

variation
Test       26968
Control    23532
NaN        20109
Name: count, dtype: int64

In [90]:
df_exp.isnull().sum()

client_id        0
variation    20109
dtype: int64

In [91]:
df_exp = df_exp.dropna(subset=['variation'])
df_exp.isnull().sum()

client_id    0
variation    0
dtype: int64

In [92]:
df_exp.variation.value_counts()

variation
Test       26968
Control    23532
Name: count, dtype: int64

In [93]:
df_exp.duplicated().sum()

np.int64(0)

In [94]:
df_exp.to_csv("clean_data/cleaned_experiment.csv",index=False)

In [95]:
df_exp.shape

(50500, 2)

## df_web cleaning

In [96]:
df_web1.head(3)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22

In [97]:
df_web2.head(3)

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48

In [98]:
#merging the two web datasets
df_web = pd.concat([df_web1, df_web2], axis=0 )

In [99]:
df_web.shape

(755405, 5)

In [100]:
df_web.duplicated().sum()

np.int64(10764)

In [101]:
df_web = df_web.drop_duplicates()
df_web.duplicated().sum()

np.int64(0)

In [102]:
df_web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [103]:
df_web.dtypes

client_id        int64
visitor_id      object
visit_id        object
process_step    object
date_time       object
dtype: object

In [104]:
df_web['date_time'] =pd.to_datetime(df_web['date_time'])
print(df_web.date_time.dtype)

datetime64[ns]

In [105]:
df_web['process_step'].value_counts()

process_step
start      234999
step_1     162797
step_2     132750
step_3     111589
confirm    102506
Name: count, dtype: int64

In [106]:
df_web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [107]:
df_web.head(10)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05
9,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43

In [108]:
df_web.to_csv("clean_data/cleaned_web.csv",index=False)

In [109]:
df_web.shape

(744641, 5)

In [110]:
df_exp.shape

(50500, 2)

## Merging df_web and df_exp

In [111]:
df= df_exp.merge(df_web, on='client_id', how='inner')
print(df.shape)

(317235, 6)

In [112]:
df.variation.value_counts()

variation
Test       176699
Control    140536
Name: count, dtype: int64

In [113]:
df.head(10)

,client_id,variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,Test,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,9988021,Test,580560515_7732621733,219729223_42518459208_211914,start,2017-04-12 18:54:43
9,9988021,Test,580560515_7732621733,219729223_42518459208_211914,start,2017-04-12 18:38:42

In [114]:
df.to_csv("clean_data/exp_web_merged.csv",index=False)

## Merging all data 
# (Web, Exp & Demo)

In [115]:
df.head()

,client_id,variation,visitor_id,visit_id,process_step,date_time
0,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,Test,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [116]:
df_demo = pd.read_csv('clean_data/cleaned_demo.csv')
df_exp = pd.read_csv('clean_data/cleaned_experiment.csv')
df_web = pd.read_csv('clean_data/cleaned_web.csv')

In [117]:
df_demo.head()

,client_id,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60,Unknown,2,45105.30,6,9
1,2304905,7.0,94.0,58,Unknown,2,110860.30,6,9
2,1439522,5.0,64.0,32,Unknown,2,52467.79,6,9
3,1562045,16.0,198.0,49,Male,2,67454.65,3,6
4,5126305,12.0,145.0,33,Female,2,103671.75,0,3

In [118]:
# step 1 : Merge web and experiment 

df1 = df_web.merge(df_exp, on='client_id', how='inner')
df1.head()

,client_id,visitor_id,visit_id,process_step,date_time,variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test

In [119]:
# step 2 : add demo data

df = df1.merge(df_demo, on='client_id', how='inner')
df.head()

,client_id,visitor_id,visit_id,process_step,date_time,variation,client_tenure_yr,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test,5.0,64.0,79,Unknown,2,189023.86,1,4
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test,5.0,64.0,79,Unknown,2,189023.86,1,4
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test,5.0,64.0,79,Unknown,2,189023.86,1,4
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test,5.0,64.0,79,Unknown,2,189023.86,1,4
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test,5.0,64.0,79,Unknown,2,189023.86,1,4

In [120]:
df.columns

Index(['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time',
       'variation', 'client_tenure_yr', 'client_tenure_month', 'client_age',
       'gender', 'num_accts', 'balance', 'calls_6_mnth', 'logons_6_mnth'],
      dtype='object')